### ISSUE TITLE
Installing 1.1 fails

### ISSUE THREAD

**Issue by josephbruni** [Kong/homebrew-kong#100]
The install fails because a missing luarocks dependency is not satisfied:

	kong 1.1.0-0 depends on lyaml 6.2.3 (not installed)
	Installing https://luarocks.org/lyaml-6.2.3-1.src.rock

	Error: Failed installing dependency: https://luarocks.org/lyaml-6.2.3-1.src.rock - Could not find library file for YAML
  	No file libyaml.a in /usr/local/lib
  	No file libyaml.dylib in /usr/local/lib
  	No file matching libyaml.so.* in /usr/local/lib
  	No file libyaml.a in /usr/lib
  	No file libyaml.dylib in /usr/lib
  	No file matching libyaml.so.* in /usr/lib
  	No file libyaml.a in /lib
  	No file libyaml.dylib in /lib
  	No file matching libyaml.so.* in /lib

I then manually installed libyaml using `brew install libyaml`. Re-attempting to install kong succeeds, however, kong does not function correctly. I have postgresql as the backend; the migrations bootstrap succeeded. After starting kong, the admin interface fails with an abrupt closing of the socket. Not sure if this latter problem is with the installation or with kong itself.

**Comment by tholu** [comment]
The `libyaml` dependency needs to be defined in the formula. The later problem looks like #99. Which MacOS version are you using?

**Comment by josephbruni** [comment]
I was attempting to install on 10.14.4.

**Comment by thibaultcha** [comment]
This should now be fixed by #101 thanks to @tholu! Mind giving it another try? Thank you!

**Comment by yuanhaisu** [comment]
I have the same problem on centos7, and manually installed libyaml using `yum install libyaml`, then Re-attempting to install kong, but it didnt work.
### Details & Logs

- Kong version : 1.1.2

`kong 1.1.2-0 depends on lyaml == 6.2.3 (not installed)
Installing https://luarocks.org/lyaml-6.2.3-1.src.rock

Error: Failed installing dependency: https://luarocks.org/lyaml-6.2.3-1.src.rock - Could not find library file for YAML
  No file libyaml.a in /usr/local/lib
  No file libyaml.a in /usr/local/lib64
  No file libyaml.so in /usr/local/lib
  No file libyaml.so in /usr/local/lib64
  No file matching libyaml.so.* in /usr/local/lib
  No file matching libyaml.so.* in /usr/local/lib64
  No file libyaml.a in /usr/lib
  No file libyaml.a in /usr/lib64
  No file libyaml.so in /usr/lib
  No file libyaml.so in /usr/lib64
  No file matching libyaml.so.* in /usr/lib
  No file matching libyaml.so.* in /usr/lib64
You may have to install YAML in your system and/or pass YAML_DIR or YAML_LIBDIR to the luarocks command.
Example: luarocks install lyaml YAML_DIR=/usr/local
make: *** [install] Error 1
`
