### ISSUE TITLE
Suggested Readme docs update

### ISSUE THREAD

**Issue by k3ithl1m** [Kong/homebrew-kong#102]
When I was installing kong with brew. I ran into some errors with Lua, and I wasnt sure how to fix it. But I realized that we can just run brew install lua before installing kong and it will solve the problem. I was thinking of doing a pull request that suggested that.

**Comment by k3ithl1m** [comment]
@thibaultcha

**Comment by Tieske** [comment]
please provide the errors. The Kong package includes all the underlying parts, and does not rely on a system version of Lua (it brings its own LuaJIT). So your fix should not be necessary.

**Comment by k3ithl1m** [comment]
When I was using brew install Kong. I had a bunch of lua errors. And after I decided to remove the entire Kong project and re install lua, did all the error disappear. Im just suggesting an alternative / side note on the doc that might help future users who wants to install it. But it’s entirely cool if you guys don’t think it’s necessary

**Comment by Tieske** [comment]
let's close this for now, if you get the errors again, please reopen.
