### ISSUE TITLE
can build in macOS  10.15

### ISSUE THREAD

**Issue by chensunny** [Kong/homebrew-kong#123]
Already downloaded: /Users/sunny/Library/Caches/Homebrew/downloads/7d367015e8aa6188277d51898003fb3507ecd6c30701b3ac87c945407ec4ca42--kong-ngx-build
==> ./kong-ngx-build --prefix /usr/local/Cellar/openresty/1.15.8.2 --openresty 1.15.8.2 --openssl 1.1.1d --luarocks 3.2.1 -j 4
Last 15 lines from /Users/sunny/Library/Logs/Homebrew/openresty/01.kong-ngx-build:
CC        luajit.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
BUILDVM   lj_ffdef.h
BUILDVM   lj_bcdef.h
BUILDVM   lj_folddef.h
make[1]: *** [lj_folddef.h] Segmentation fault: 11
make[1]: *** Deleting file `lj_folddef.h'
make[1]: *** Waiting for unfinished jobs....
BUILDVM   lj_recdef.h
make: *** [default] Error 2
ERROR: failed to run command: gmake -j4 TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT -msse4.2' CC=cc PREFIX=/usr/local/Cellar/openresty/1.15.8.2/openresty/luajit

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues

**Comment by anuragmath** [comment]
I m facing similar issue on macOS 10.15.

**Comment by nixuw** [comment]
me too!

> Last 15 lines from /Users/wuxin/Library/Logs/Homebrew/openresty/01.kong-ngx-build:
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
BUILDVM   lj_ffdef.h
BUILDVM   lj_bcdef.h
BUILDVM   lj_folddef.h
BUILDVM   lj_recdef.h
BUILDVM   lj_libdef.h
BUILDVM   jit/vmdef.lua
make[1]: *** [lj_folddef.h] Segmentation fault: 11
make[1]: *** Deleting file `lj_folddef.h'
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
ERROR: failed to run command: gmake -j8 TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT -msse4.2' CC=cc PREFIX=/usr/local/Cellar/openresty/1.15.8.2/openresty/luajit

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues

**Comment by wssaidong** [comment]
brew install kong
==> Installing kong from kong/kong
==> Installing dependencies for kong/kong/kong: kong/kong/openresty@1.15.8.2 and libyaml
==> Installing kong/kong/kong dependency: kong/kong/openresty@1.15.8.2
==> Downloading https://raw.githubusercontent.com/Kong/openresty-build-tools/0.0
Already downloaded: /Users/cai/Library/Caches/Homebrew/downloads/7d367015e8aa6188277d51898003fb3507ecd6c30701b3ac87c945407ec4ca42--kong-ngx-build
==> ./kong-ngx-build --prefix /usr/local/Cellar/openresty/1.15.8.2 --openresty 1
Last 15 lines from /Users/cai/Library/Logs/Homebrew/openresty/01.kong-ngx-build:
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
BUILDVM   lj_ffdef.h
BUILDVM   lj_bcdef.h
BUILDVM   lj_folddef.h
BUILDVM   lj_recdef.h
BUILDVM   lj_libdef.h
BUILDVM   jit/vmdef.lua
make[1]: *** [lj_folddef.h] Segmentation fault: 11
make[1]: *** Deleting file `lj_folddef.h'
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
ERROR: failed to run command: gmake -j8 TARGET_STRIP=@: CCDEBUG=-g XCFLAGS='-DLUAJIT_ENABLE_LUA52COMPAT -msse4.2' CC=cc PREFIX=/usr/local/Cellar/openresty/1.15.8.2/openresty/luajit

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues

**Comment by tomzmyslo** [comment]
There is a workaround in issue https://github.com/Kong/homebrew-kong/issues/121#issuecomment-551256759 by @seonixx.

**Comment by guanlan** [comment]
Duplicated to #121 , closing this
