### ISSUE TITLE
Unable to install kong on macOS 10.15.4

### ISSUE THREAD

**Issue by tzssangglass** [Kong/homebrew-kong#135]
Unable to install kong on macOS  10.15.4
$brew install kong
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from e94fff894 to 0859115a2.
No changes to formulae.

==> Installing kong from kong/kong
==> Installing dependencies for kong/kong/kong: kong/kong/openresty@1.15.8.2 and libyaml
==> Installing kong/kong/kong dependency: kong/kong/openresty@1.15.8.2
==> Downloading https://github.com/Kong/kong-build-tools/archive/3.1.3.zip
==> Downloading from https://codeload.github.com/Kong/kong-build-tools/zip/3.1.3
######################################################################## 100.0%
==> ./kong-ngx-build --prefix /usr/local/Cellar/openresty/1.15.8.2 --openresty 1
Last 15 lines from /Users/{username}/Library/Logs/Homebrew/openresty/01.kong-ngx-build:
2020-04-03 23:31:30 +0800

./kong-ngx-build
--prefix /usr/local/Cellar/openresty/1.15.8.2
--openresty 1.15.8.2
--openssl 1.1.1d
--luarocks 3.2.1
-j 12

NOTICE: Downloading the components now...
/private/tmp/openresty-20200403-68097-18ajwl8/kong-build-tools-3.1.3/openresty-build-tools/work /private/tmp/openresty-20200403-68097-18ajwl8/kong-build-tools-3.1.3/openresty-build-tools
WARN: OpenSSL source not found, downloading...
tar: Error opening archive: Unrecognized archive format

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues

**Comment by primableatom** [comment]
I am also facing the same issue since a couple of days

**Comment by arnabiitr** [comment]
Same issue on 10.15.4 
% brew tap kong/kong
==> Tapping kong/kong
Cloning into '/usr/local/Homebrew/Library/Taps/kong/homebrew-kong'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 771 (delta 11), reused 15 (delta 6), pack-reused 741
Receiving objects: 100% (771/771), 111.41 KiB | 1.66 MiB/s, done.
Resolving deltas: 100% (253/253), done.
Tapped 3 formulae (31 files, 165.2KB).
arnabiitr@Arnabs-MacBook-Pro-2 Downloads % brew install kong
==> Installing kong from kong/kong
==> Installing dependencies for kong/kong/kong: pcre, coreutils, kong/kong/openresty@1.15.8.2 and libyaml
==> Installing kong/kong/kong dependency: pcre
==> Downloading https://homebrew.bintray.com/bottles/pcre-8.44.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/f8/f8ac266e04f984fa55091a43f0fdc39a40d57c2489d289a186c88ccedaba7eeb?__gda__=exp=15
######################################################################## 100.0%
==> Pouring pcre-8.44.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/pcre/8.44: 204 files, 5.5MB
==> Installing kong/kong/kong dependency: coreutils
==> Downloading https://homebrew.bintray.com/bottles/coreutils-8.32.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/67/67a4452d75a1882bd7fb977b384204edfa2758276d66290e595487922368e093?__gda__=exp=15
######################################################################## 100.0%
==> Pouring coreutils-8.32.catalina.bottle.tar.gz
==> Caveats
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
==> Summary
🍺  /usr/local/Cellar/coreutils/8.32: 476 files, 9.2MB
==> Installing kong/kong/kong dependency: kong/kong/openresty@1.15.8.2
==> Downloading https://github.com/Kong/kong-build-tools/archive/3.1.3.zip
==> Downloading from https://codeload.github.com/Kong/kong-build-tools/zip/3.1.3
######################################################################## 100.0%
==> ./kong-ngx-build --prefix /usr/local/Cellar/openresty/1.15.8.2 --openresty 1.15.8.2 --openssl 1.1.1d --luarocks 3.2.1 -j 16
Last 15 lines from /Users/arnabiitr/Library/Logs/Homebrew/openresty/01.kong-ngx-build:
2020-04-05 00:53:19 -0400

./kong-ngx-build
--prefix /usr/local/Cellar/openresty/1.15.8.2
--openresty 1.15.8.2
--openssl 1.1.1d
--luarocks 3.2.1
-j 16

NOTICE: Downloading the components now...
/private/tmp/openresty-20200405-4392-nhirml/kong-build-tools-3.1.3/openresty-build-tools/work /private/tmp/openresty-20200405-4392-nhirml/kong-build-tools-3.1.3/openresty-build-tools
WARN: OpenSSL source not found, downloading...
tar: Error opening archive: Unrecognized archive format

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues

**Comment by dmylangam** [comment]
Same problem here... need advice on how to resolve this ASAP.

**Comment by jury09** [comment]
Same issue on 10.15.1

**Comment by primableatom** [comment]
I stopped fighting with it and installed a docker image from kong https://hub.docker.com/_/kong
I suggest you go the same route.

**Comment by tzssangglass** [comment]
> I stopped fighting with it and installed a docker image from kong https://hub.docker.com/_/kong
> I suggest you go the same route.


Thank you for your suggestion, I know this is feasible, but I want to install kong on mac to develop plugins, and can use ZeroBrane Studio to debug kong source code, using docker will be a little more troublesome.

**Comment by vinkin** [comment]
did you solve this problem ? can you show us how did you solve it ?
