### ISSUE TITLE
Failed installing dependency while installing kong using brew

### ISSUE THREAD

**Issue by Jaikrat** [Kong/homebrew-kong#170]
Error: Failed installing dependency: https://luarocks.org/luasec-1.0.1-1.src.rock - Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/luasec-1.0.1-1.src.rock - failed downloading https://luarocks.org/luasec-1.0.1-1.src.rock

Commands fired:

$ brew tap kong/kong  
$ brew install kong

as given at https://docs.konghq.com/install/macos/?_ga=2.26378104.459741268.1623777903-1866422387.1623213412

**Comment by kikito** [comment]
Hello @Jaikrat , that is a failure on an external dependency (the `luarocks` servers).

I am afraid there's little we can do on this repo in order to fix that.

You will have to retry a bit later.
