### ISSUE TITLE
Error: Failed installing dependency: https://luarocks.org/lyaml-6.2.7-1.src.rock

### ISSUE THREAD

**Issue by vitor-l** [Kong/homebrew-kong#174]
Hello! I'm trying to install _kong_ in my macOS Big Sur (Version 11.5). 

Input in my terminal:
> brew tap kong/kong

Output: OK!

Input in my terminal:
> brew install kong

Output:

```bash
Error: Failed installing dependency: https://luarocks.org/lyaml-6.2.7-1.src.rock - Could not find library file for YAML
  No file libyaml.a in /usr/local/lib
  No file libyaml.dylib in /usr/local/lib
  No file matching libyaml.so.* in /usr/local/lib
  No file libyaml.a in /usr/lib
  No file libyaml.dylib in /usr/lib
  No file matching libyaml.so.* in /usr/lib
  No file libyaml.a in /lib
  No file libyaml.dylib in /lib
  No file matching libyaml.so.* in /lib
You may have to install YAML in your system and/or pass YAML_DIR or YAML_LIBDIR to the luarocks command.
Example: luarocks install lyaml YAML_DIR=/usr/local
```

**Comment by kikito** [comment]
That might have been a temporary problem in the luarocks server. Please retry.

**Comment by vitor-l** [comment]
I tried yesterday and It did not work...

**Comment by kikito** [comment]
@vitor-l I just merged a fix (#176) so the formula has changed. Please try:
```
brew uninstall openresty
brew uninstall kong/kong/openresty
brew untap kong/kong
brew tap kong/kong
brew install kong
```

**Comment by wuyachao** [comment]
> Nope... still an error.
> 
> ```shell
> kong 2.5.0-0 depends on lyaml 6.2.7 (not installed)
> Installing https://luarocks.org/lyaml-6.2.7-1.src.rock
> 
> Error: Failed installing dependency: https://luarocks.org/lyaml-6.2.7-1.src.rock - Could not find library file for YAML
>   No file libyaml.a in /usr/local/lib
>   No file libyaml.dylib in /usr/local/lib
>   No file matching libyaml.so.* in /usr/local/lib
>   No file libyaml.a in /usr/lib
>   No file libyaml.dylib in /usr/lib
>   No file matching libyaml.so.* in /usr/lib
>   No file libyaml.a in /lib
>   No file libyaml.dylib in /lib
>   No file matching libyaml.so.* in /lib
> You may have to install YAML in your system and/or pass YAML_DIR or YAML_LIBDIR to the luarocks command.
> Example: luarocks install lyaml YAML_DIR=/usr/local
> 
> Do not report this issue to Homebrew/brew or Homebrew/core!
> ```

1.luarocks install lyaml
```
Error: Could not find library file for YAML
  No file libyaml.a in /usr/local/lib
  No file libyaml.dylib in /usr/local/lib
  No file matching libyaml.so.* in /usr/local/lib
```

2.brew info libyaml
`/opt/homebrew/Cellar/libyaml/0.2.5`

3.luarocks install lyaml YAML_LIBDIR=/opt/homebrew/Cellar/libyaml/0.2.5/lib/ YAML_INCDIR=/opt/homebrew/Cellar/libyaml/0.2.5/include/ 
`It looks like sucess:lyaml 6.2.7-1 is now installed in /opt/homebrew/Cellar/openresty@1.19.3.2/1.19.3.2/luarocks`

4.brew install kong
```
it still an error:
No file libyaml.a in /usr/local/lib
  No file libyaml.dylib in /usr/local/lib
  No file matching libyaml.so.* in /usr/local/lib
  No file libyaml.a in /usr/lib
  No file libyaml.dylib in /usr/lib
  No file matching libyaml.so.* in /usr/lib
  No file libyaml.a in /lib
  No file libyaml.dylib in /lib
  No file matching libyaml.so.* in /lib
```

5.ln -s /opt/homebrew/Cellar/libyaml/0.2.5/lib/* /usr/local/lib
`brew install kong`

brew install kong                                            
```
==> Installing kong from kong/kong
==> Downloading https://download.konghq.com/gateway-src/kong-2.5.0.tar.gz
Already downloaded: /Users/wuyachao/Library/Caches/Homebrew/downloads/2f8ba8914e27f26f25f76ebd16a3453474274690b35bee36621f0cde3a373335--kong-2.5.0.tar.gz
==> Patching
==> /opt/homebrew/opt/openresty@1.19.3.2/luarocks/bin/luarocks --tree=/opt/homebrew/Cellar/kong/2.5.0 make CRYPTO_DIR=/opt/homebrew/opt/openresty@1.19.3.2/openssl OPENS
🍺  /opt/homebrew/Cellar/kong/2.5.0: 1,221 files, 10.0MB, built in 1 minute 30 seconds
```

**Comment by fffonion** [comment]
I made another attempt on the `fix/test-opt_lib`, could you test one more time @vitor-l ?

**Comment by vitor-l** [comment]
Hello @fffonion, sorry for the late response. So I did a `git fetch --all` and `git pull origin fix/test-opt_lib`. At Formula folder, I executed `brew install ./kong.rb`.

Output for `brew install ./kong.rb`:

```bash
Error: Failed to load cask: ./kong.rb
Cask 'kong' is unreadable: wrong constant name #<Class:0x000000014b1b66c8>
Warning: Treating ./kong.rb as a formula.
==> Downloading https://download.konghq.com/gateway-src/kong-2.5.0.tar.gz
Already downloaded: /Users/vitorlgs/Library/Caches/Homebrew/downloads/2f8ba8914e27f26f25f76ebd16a3453474274690b35bee36621f0cde3a373335--kong-2.5.0.tar.gz
==> Patching
==> /opt/homebrew/opt/openresty@1.19.3.2/luarocks/bin/luarocks --tree=/opt/homebrew/Cellar/kong/2.5.0 make CRYPTO_DIR=/opt/homebrew/opt/openresty@1.19.3.2/openssl OPENSSL_DIR=/
🍺  /opt/homebrew/Cellar/kong/2.5.0: 1,221 files, 10.0MB, built in 1 minute 41 seconds
==> `brew cleanup` has not been run in 30 days, running now...
Removing: /Users/vitorlgs/Library/Caches/Homebrew/c-ares--1.17.1... (164.8KB)
Removing: /Users/vitorlgs/Library/Caches/Homebrew/cmake--3.21.1... (17MB)
Removing: /Users/vitorlgs/Library/Caches/Homebrew/glib--2.68.3... (6.5MB)
Removing: /Users/vitorlgs/Library/Caches/Homebrew/m4--1.4.18... (228.4KB)
Removing: /Users/vitorlgs/Library/Caches/Homebrew/mutagen-beta--0.12.0-beta4.tar.gz... (78.4MB)
Removing: /Users/vitorlgs/Library/Caches/Homebrew/node--16.6.1... (12.5MB)
Removing: /Users/vitorlgs/Library/Caches/Homebrew/openssl@1.1--1.1.1k... (5.2MB)
Removing: /Users/vitorlgs/Library/Caches/Homebrew/webp--1.2.0... (745.8KB)
Removing: /Users/vitorlgs/Library/Logs/Homebrew/coreutils... (64B)
Removing: /Users/vitorlgs/Library/Logs/Homebrew/wxmac... (64B)
Removing: /Users/vitorlgs/Library/Logs/Homebrew/elixir... (64B)
Removing: /Users/vitorlgs/Library/Logs/Homebrew/libyaml... (64B)
Removing: /Users/vitorlgs/Library/Logs/Homebrew/erlang... (64B)
Removing: /Users/vitorlgs/Library/Logs/Homebrew/luarocks... (64B)
Removing: /Users/vitorlgs/Library/Logs/Homebrew/lua... (64B)
Removing: /Users/vitorlgs/Library/Logs/Homebrew/openresty@1.19.3.1... (4 files, 4.9MB)
```

Output for `brew --version`:

```bash
Homebrew 3.2.9
Homebrew/homebrew-core (git revision fa395c6627; last commit 2021-08-27)
Homebrew/homebrew-cask (git revision 606ed52390; last commit 2021-08-27)
```

Output for `brew info libyaml`:

```bash
libyaml: stable 0.2.5 (bottled)
YAML Parser
https://github.com/yaml/libyaml
/opt/homebrew/Cellar/libyaml/0.2.5 (10 files, 369.9KB) *
  Poured from bottle on 2021-08-27 at 15:02:02
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libyaml.rb
License: MIT
==> Dependencies
Build: autoconf ✘, automake ✘, libtool ✘
==> Analytics
install: 73,270 (30 days), 218,603 (90 days), 1,026,825 (365 days)
install-on-request: 13,656 (30 days), 42,768 (90 days), 217,333 (365 days)
build-error: 0 (30 days)
```

Output for `ls /usr/local/lib | grep yaml` is empty

**Comment by fffonion** [comment]
```
🍺  /opt/homebrew/Cellar/kong/2.5.0: 1,221 files, 10.0MB, built in 1 minute 41 seconds
```
Looks like the formula built successfully, which looks good. Are you able to use Kong after it's being installed? @vitor-l

**Comment by vitor-l** [comment]
I did not have the change to try, but as you said, @fffonion, the installation was ok. I did not test because I dropped the project using Kong... But, if I have any problems, I'll let you know. Thanks for the help and sorry for the late response.

**Comment by vitor-l** [comment]
Hello, @fffonion!

When I run `kong`, I get this output:

```bash
env: resty: No such file or directory
```

**Comment by fffonion** [comment]
@vitor-l That might be a PATH issue, M1 version of homebrew has its `bin` path as `/opt/homebrew/bin`. Do you have that
path in your shell's `PATH` environment variable? That should be a generic configuration on M1 not just Kong, basically
all other binaries installed by homebrew would be inaccessible without that config.

**Comment by vitor-l** [comment]
@fffonion, how can I check that? Just going to `/opt/homebrew/bin`?

**Comment by fffonion** [comment]
@vitor-l You can check it by running `echo $PATH` in your shell.
And if you don't remember configuring so, then
you haven't configured it : ) The path doesn't come by default from macOS. You can use https://github.com/Homebrew/discussions/discussions/545 as a guide.

**Comment by fffonion** [comment]
@vitor-l Hmm I see 🤔 . Could you check if `resty` is in `/opt/homebrew/bin`?
```shell
ls /opt/homebrew/bin | grep resty
```

**Comment by vitor-l** [comment]
@fffonion, `resty` is not there. The output is empty.

**Comment by fffonion** [comment]
@vitor-l Okay, that might be the issue. But I didn't see why it's not there per https://github.com/Kong/homebrew-kong/blob/master/Formula/openresty%401.19.3.2.rb#L51. Are you able to use any others like `nginx` or `luarocks`?
Did you observe any information when installing Kong that says something like "is not linked"? Could you try
`brew linke kong` 🤔 ?

**Comment by vitor-l** [comment]
@fffonion, I did not observe anything like that. It seems that `kon` was already linked.

```bash
❯ brew link kong
Warning: Already linked: /opt/homebrew/Cellar/kong/2.5.1
To relink, run:
  brew unlink kong && brew link kong
❯ brew unlink kong && brew link kong
Unlinking /opt/homebrew/Cellar/kong/2.5.1... 671 symlinks removed.
Linking /opt/homebrew/Cellar/kong/2.5.1... 671 symlinks created.
```
