### ISSUE TITLE
Kong 2.5.0 formula doesn't bump dependencies

### ISSUE THREAD

**Issue by adviri** [Kong/homebrew-kong#175]
According to [Kong's .requirement file](https://github.com/Kong/kong/blob/master/.requirements) Kong 2.5.0 should use `openresty 1.19.3.2` and `kong-build-tools 4.20.0`

**Comment by adviri** [comment]
Pull request: https://github.com/Kong/homebrew-kong/pull/176

**Comment by kikito** [comment]
Thanks for this, will review

**Comment by kikito** [comment]
Should be fixed by #176
