### ISSUE TITLE
Kong Install Timeout - MacOS 11.6

### ISSUE THREAD

**Issue by c3bryant** [Kong/homebrew-kong#182]
Hello,
I am evaluating Kong API and trying to install Kong for MacOS. I have run into an issue when installing Kong as described in the [MacOS installation guide](https://docs.konghq.com/install/macos/)

The specific error is:
```
curl: (7) Failed to connect to ftp.pcre.org port 443: Operation timed out
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues
```

Full log:
```
cbryant$ brew tap kong/kong
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 2 formulae.
==> Updated Casks
Updated 2 casks.

cbryant$ brew install kong
==> Downloading https://github.com/Kong/kong-build-tools/archive/4.20.0.zip
Already downloaded: /Users/cbryant/Library/Caches/Homebrew/downloads/698e66dbd52deaa29c50443f454861925d838641de174c978373617a76e66463--kong-build-tools-4.20.0.zip
==> Downloading https://download.konghq.com/gateway-src/kong-2.6.0.tar.gz
Already downloaded: /Users/cbryant/Library/Caches/Homebrew/downloads/c6ffcd8492ddb56dce073544569c9f7a44a53a3fb18ad7a1a316e9d25d06ef2b--kong-2.6.0.tar.gz
==> Installing kong from kong/kong
==> Installing dependencies for kong/kong/kong: kong/kong/openresty@1.19.3.2
==> Installing kong/kong/kong dependency: kong/kong/openresty@1.19.3.2
/usr/local/Homebrew/Library/Taps/kong/homebrew-kong/Formula/openresty@1.19.3.2.rb:46: warning: conflicting chdir during another chdir block
==> ./kong-ngx-build --prefix /usr/local/Cellar/openresty@1.19.3.2/1.19.3.2 --openresty 1.19.3.2 --opens
Last 15 lines from /Users/cbryant/Library/Logs/Homebrew/openresty@1.19.3.2/01.kong-ngx-build:
--openssl 1.1.1k
--luarocks 3.5.0
--pcre 8.44
-j 12

NOTICE: Downloading the components now...
/private/tmp/openrestyA1.19.3.2-20211104-50934-1dw1weo/kong-build-tools-4.20.0/openresty-build-tools/work /private/tmp/openrestyA1.19.3.2-20211104-50934-1dw1weo/kong-build-tools-4.20.0/openresty-build-tools
WARN: OpenSSL source not found, downloading...
WARN: Vanilla OpenResty found but patches requested, removing Makefile...
WARN: OpenResty source not found, downloading...
/private/tmp/openrestyA1.19.3.2-20211104-50934-1dw1weo/kong-build-tools-4.20.0/openresty-build-tools/work/openresty-1.19.3.2/bundle /private/tmp/openrestyA1.19.3.2-20211104-50934-1dw1weo/kong-build-tools-4.20.0/openresty-build-tools/work /private/tmp/openrestyA1.19.3.2-20211104-50934-1dw1weo/kong-build-tools-4.20.0/openresty-build-tools
NOTICE: Updating lua-resty-dns to unreleased version
/private/tmp/openrestyA1.19.3.2-20211104-50934-1dw1weo/kong-build-tools-4.20.0/openresty-build-tools/work /private/tmp/openrestyA1.19.3.2-20211104-50934-1dw1weo/kong-build-tools-4.20.0/openresty-build-tools
WARN: PCRE source not found, downloading...
curl: (7) Failed to connect to ftp.pcre.org port 443: Operation timed out

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues

cbryant$ kong version
zsh: command not found: kong
```

I see the same error when running `brew install openresty`. Please advise.

Thank you

**Comment by eli-tsikel** [comment]
+1

**Comment by kikito** [comment]
Hello, thank you for reporting this, we'll give this a look. It seems the servers at https://ftp.pcre.org/ are down , we'll see what we can do about that.

**Comment by lavanya2290** [comment]
+1
NOTICE: Downloading the components now...
/private/tmp/openrestyA1.19.3.2-20211113-37998-1d9ksxr/kong-build-tools-4.20.0/openresty-build-tools/work /private/tmp/openrestyA1.19.3.2-20211113-37998-1d9ksxr/kong-build-tools-4.20.0/openresty-build-tools
WARN: OpenSSL source not found, downloading...
WARN: Vanilla OpenResty found but patches requested, removing Makefile...
WARN: OpenResty source not found, downloading...
/private/tmp/openrestyA1.19.3.2-20211113-37998-1d9ksxr/kong-build-tools-4.20.0/openresty-build-tools/work/openresty-1.19.3.2/bundle /private/tmp/openrestyA1.19.3.2-20211113-37998-1d9ksxr/kong-build-tools-4.20.0/openresty-build-tools/work /private/tmp/openrestyA1.19.3.2-20211113-37998-1d9ksxr/kong-build-tools-4.20.0/openresty-build-tools
NOTICE: Updating lua-resty-dns to unreleased version
/private/tmp/openrestyA1.19.3.2-20211113-37998-1d9ksxr/kong-build-tools-4.20.0/openresty-build-tools/work /private/tmp/openrestyA1.19.3.2-20211113-37998-1d9ksxr/kong-build-tools-4.20.0/openresty-build-tools
WARN: PCRE source not found, downloading...
curl: (7) Failed to connect to ftp.pcre.org port 443: Operation timed out

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues

**Comment by lavanya2290** [comment]
May be fixed by #183 works fine and I tested, pls merge ASAP @kikito

**Comment by haider0324** [comment]
Hi @kikito ,

I am still facing this issue in macOS Monterey 12.0.1.  Couple of months back it's work fine for me on another machine. Now it didn't and gives following error

WARN: PCRE source not found, downloading...
curl: (28) Failed to connect to ftp.pcre.org port 443: Operation timed out

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/kong/homebrew-kong/issues

Thanks

**Comment by haider0324** [comment]
Great Thanks! @gszr , you save my day 🙂

**Comment by lavanya2290** [comment]
Thanks @haider0324
