### ISSUE TITLE
admin-kong-default.key: Permission denied

### ISSUE THREAD

**Issue by rosskukulinski** [Kong/homebrew-kong#194]
I'm unable to get kong to start on my M1 architecture with a permission denied error on certificates.  I followed [the docs](https://docs.konghq.com/gateway/2.7.x/install-and-run/macos/) for running Kong in db-less mode.

First I installed Kong via brew:

> brew tap kong/kong
> brew install kong

Then I generated a default config and customized for declarative config

> kong config init

```
$ cat kong.yml 
# ------------------------------------------------------------------------------
# This is an example file to get you started with using
# declarative configuration in Kong.
# ------------------------------------------------------------------------------
_format_version: "2.1"
_transform: true
declarative_config = /Users/ross.kukulinski@konghq.com/dev/kong-osx/kong.yml
database = off
```

Then I started Kong using my config file

```
kong start -c /Users/ross.kukulinski@konghq.com/dev/kong-osx/kong.yml --v --vv
2022/02/18 08:30:14 [verbose] Kong: 2.7.1
2022/02/18 08:30:14 [verbose] reading config file at /Users/ross.kukulinski@konghq.com/dev/kong-osx/kong.yml
2022/02/18 08:30:14 [verbose] prefix in use: /opt/homebrew/opt/kong
2022/02/18 08:30:14 [verbose] preparing nginx prefix directory at /opt/homebrew/opt/kong
2022/02/18 08:30:14 [verbose] SSL enabled on 
2022/02/18 08:30:14 [verbose] proxy SSL certificate found at /opt/homebrew/opt/kong/ssl/kong-default.crt
2022/02/18 08:30:14 [verbose] generating /opt/homebrew/opt/kong/ssl/kong-default-ecdsa.crt SSL certificate (
Error: 
...homebrew/share/lua/5.1/kong/cmd/utils/prefix_handler.lua:156: /opt/homebrew/opt/kong/ssl/kong-default-ecdsa.key: Permission denied
stack traceback:
	[C]: in function 'assert'
	...homebrew/share/lua/5.1/kong/cmd/utils/prefix_handler.lua:156: in function 'gen_default_ssl_cert'
	...homebrew/share/lua/5.1/kong/cmd/utils/prefix_handler.lua:392: in function 'prepare_prefix'
	/opt/homebrew/share/lua/5.1/kong/cmd/start.lua:24: in function 'cmd_exec'
	/opt/homebrew/share/lua/5.1/kong/cmd/init.lua:88: in function </opt/homebrew/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/opt/homebrew/share/lua/5.1/kong/cmd/init.lua:88: in function </opt/homebrew/share/lua/5.1/kong/cmd/init.lua:45>
	/opt/homebrew/bin/kong:10: in function 'file_gen'
	init_worker_by_lua:50: in function <init_worker_by_lua:48>
	[C]: in function 'xpcall'
	init_worker_by_lua:57: in function <init_worker_by_lua:55>
```

**Comment by jdugaw-vitu** [comment]
@rosskukulinski I ended up going with the Postrgres based installation and had similar(ish) issues until I logged in as root. Then ran `kong` commands as root and all my issues went away. 

There is a buried comment in one of the docs about `kong` needing to run as `root` because of the `nginx` permission. Or maybe it was `nginx`. Sorry I was scrambling trying to get unblocked and didn't bread crumb the solution very well. 

But when I ran the postgres installation in a root session having logged in as ROOT it worked. I'm unblocked and behind schedule on a delivery. If I an remember to do it, I'll try your use case again.

Best of luck

**Comment by jdugaw-vitu** [comment]
Also the MacOS installation guide using Docker is wrong. It defaults to a amd/arch64 which doesn't work when your machine is arm/arch64. 

GRRRR - love the performance but I should have thought ahead when buying my mac. :(

**Comment by curiositycasualty** [comment]
> It seems you are using your declarative config file, kong.**yml**, to start kong whereas you _in fact_ need to use a kong.**conf** file.

> Moreover, you should specify configs such as:
> ```ini
> database = off
> declarative_config = /Users/ross.kukulinski@konghq.com/dev/kong-osx/kong.yml
> ```
> **not** in `kong.yml` file but in `kong.conf` file.

> `kong.yml` should be used only for creating resources such as services, routes etc.
