### ISSUE TITLE
lua.h version mismatch (interpreter: ; lua.h: 5.1)

### ISSUE THREAD

**Issue by jjuradogi** [Kong/homebrew-kong#49]
`unknown:kong username$ brew install kong
==> Installing kong from mashape/kong
==> Installing dependencies for mashape/kong/kong: mashape/kong/luarocks
==> Installing mashape/kong/kong dependency: mashape/kong/luarocks
==> Downloading https://luarocks.org/releases/luarocks-2.4.2.tar.gz
Already downloaded: /Users/username/Library/Caches/Homebrew/luarocks-2.4.2.tar.gz
==> Patching
patching file Makefile
==> ./configure --prefix=/usr/local/Cellar/luarocks/2.4.2 --rocks-tree=/usr/local/opt/kong --sysconfdir=/usr/local/Cellar/lu
Last 15 lines from /Users/username/Library/Logs/Homebrew/luarocks/01.configure:
--with-lua=/usr/local/opt/openresty/luajit
--with-lua-include=/usr/local/opt/openresty/luajit/include/luajit-2.1
--lua-suffix=jit

Lua version detected:
Lua interpreter found: /usr/local/opt/openresty/luajit/bin/luajit...
Checking Lua includes...
lua.h found in /usr/local/opt/openresty/luajit/include/luajit-2.1/lua.h
Checking if Lua header version matches that of the interpreter...
no
lua.h version mismatch (interpreter: ; lua.h: 5.1).
You may want to use the flag --with-lua or --with-lua-include. See --help.

configure failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mashape/homebrew-kong/issues`

I'm having this trouble just before using `brew tap mashape/kong` and then `brew install kong`.

**Comment by scguoi** [comment]
the same problem? does it solved?

**Comment by tholu** [comment]
Is this issue still relevant?

**Comment by Mryashbhardwaj** [comment]
yes its relevant
