### ISSUE TITLE
brew install kong(1.0.0) failing(Mac OS 10.14)

### ISSUE THREAD

**Issue by kartikey91** [Kong/homebrew-kong#85]
"""brew install kong -vv
==> Installing kong from kong/kong
==> Installing dependencies for kong/kong/kong: kong/kong/openresty
==> Installing kong/kong/kong dependency: kong/kong/openresty
/usr/bin/sandbox-exec -f /private/tmp/homebrew20181226-61461-919yl7.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.61.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/kong/homebrew-kong/Formula/openresty.rb --verbose
==> Downloading https://openresty.org/download/openresty-1.13.6.2.tar.gz
Already downloaded: /Users/apple/Library/Caches/Homebrew/downloads/f5bb16df194ab3757f342a23acd27d902bc06ef79b4de62c2f689d380d790d91--openresty-1.13.6.2.tar.gz
==> Verifying f5bb16df194ab3757f342a23acd27d902bc06ef79b4de62c2f689d380d790d91--openresty-1.13.6.2.tar.gz checksum
tar xf /Users/apple/Library/Caches/Homebrew/downloads/f5bb16df194ab3757f342a23acd27d902bc06ef79b4de62c2f689d380d790d91--openresty-1.13.6.2.tar.gz -C /private/tmp/d20181226-61463-1m366nn
cp -pR /private/tmp/d20181226-61463-1m366nn/openresty-1.13.6.2/. /private/tmp/openresty-20181226-61463-1fysxzy/openresty-1.13.6.2
chmod -Rf +w /private/tmp/d20181226-61463-1m366nn
==> Cloning https://github.com/Kong/openresty-patches.git
Updating /Users/apple/Library/Caches/Homebrew/openresty--openresty-patches--git
git config remote.origin.url https://github.com/Kong/openresty-patches.git
git config remote.origin.fetch \+refs/heads/master:refs/remotes/origin/master
git config remote.origin.tagOpt --no-tags
git fetch origin
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up to date with 'origin/master'.
git reset --hard origin/master
HEAD is now at a4fe140 fix(transparent) avoid redefinition of kernel ipv6 definitions (bis) (#33)
cp -pR /Users/apple/Library/Caches/Homebrew/openresty--openresty-patches--git/LICENSE /private/tmp/d20181226-61463-51fmgx/LICENSE
cp -pR /Users/apple/Library/Caches/Homebrew/openresty--openresty-patches--git/.ci/. /private/tmp/d20181226-61463-51fmgx/.ci
cp -pR /Users/apple/Library/Caches/Homebrew/openresty--openresty-patches--git/patches/. /private/tmp/d20181226-61463-51fmgx/patches
cp -pR /Users/apple/Library/Caches/Homebrew/openresty--openresty-patches--git/README.md /private/tmp/d20181226-61463-51fmgx/README.md
cp -pR /Users/apple/Library/Caches/Homebrew/openresty--openresty-patches--git/.git/. /private/tmp/d20181226-61463-51fmgx/.git
cp -pR /Users/apple/Library/Caches/Homebrew/openresty--openresty-patches--git/.travis.yml /private/tmp/d20181226-61463-51fmgx/.travis.yml
cp -pR /private/tmp/d20181226-61463-51fmgx/LICENSE /private/tmp/openresty--openresty-patches-20181226-61463-vvem7t/LICENSE
cp -pR /private/tmp/d20181226-61463-51fmgx/.ci/. /private/tmp/openresty--openresty-patches-20181226-61463-vvem7t/.ci
cp -pR /private/tmp/d20181226-61463-51fmgx/patches/. /private/tmp/openresty--openresty-patches-20181226-61463-vvem7t/patches
cp -pR /private/tmp/d20181226-61463-51fmgx/README.md /private/tmp/openresty--openresty-patches-20181226-61463-vvem7t/README.md
cp -pR /private/tmp/d20181226-61463-51fmgx/.git/. /private/tmp/openresty--openresty-patches-20181226-61463-vvem7t/.git
cp -pR /private/tmp/d20181226-61463-51fmgx/.travis.yml /private/tmp/openresty--openresty-patches-20181226-61463-vvem7t/.travis.yml
chmod -Rf +w /private/tmp/d20181226-61463-51fmgx
==> patch -p1 < /private/tmp/openresty--openresty-patches-20181226-61463-vvem7t/patches/1.13.6.2/nginx-1.13.6_03-log-tls.patch
patching file nginx-1.13.6/src/event/ngx_event_openssl.c
==> patch -p1 < /private/tmp/openresty--openresty-patches-20181226-61463-vvem7t/patches/1.13.6.2/ngx_stream_lua-0.0.5_06-ssl-cert.patch
patching file ngx_stream_lua-0.0.5/config
Hunk #1 FAILED at 342.
Hunk #2 FAILED at 386.
2 out of 2 hunks FAILED -- saving rejects to file ngx_stream_lua-0.0.5/config.rej
patching file ngx_stream_lua-0.0.5/src/api/ngx_stream_lua_api.h
patching file ngx_stream_lua-0.0.5/src/ddebug.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_api.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_args.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_args.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_balancer.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_balancer.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_cache.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_cache.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_clfactory.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_clfactory.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_common.h
Hunk #2 succeeded at 126 (offset 5 lines).
Hunk #3 succeeded at 234 (offset 5 lines).
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_config.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_config.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_consts.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_consts.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_contentby.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_contentby.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_control.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_control.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_coroutine.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_coroutine.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_ctx.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_ctx.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_directive.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_directive.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_exception.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_exception.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_initby.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_initby.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_initworkerby.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_initworkerby.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_lex.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_lex.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_log.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_log.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_logby.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_logby.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_misc.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_misc.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_module.c
Hunk #2 FAILED at 28.
Hunk #3 succeeded at 359 (offset -1 lines).
Hunk #4 succeeded at 731 (offset 4 lines).
1 out of 4 hunks FAILED -- saving rejects to file ngx_stream_lua-0.0.5/src/ngx_stream_lua_module.c.rej
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_output.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_output.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_pcrefix.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_pcrefix.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_phase.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_phase.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_probe.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_regex.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_regex.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_script.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_script.h
can't find file to patch at input line 1220
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/ngx_stream_lua-0.0.5/src/ngx_stream_lua_semaphore.c b/ngx_stream_lua-0.0.5/src/ngx_stream_lua_semaphore.c
|index 207015b..c9b1ecd 100644
|--- a/ngx_stream_lua-0.0.5/src/ngx_stream_lua_semaphore.c
|+++ b/ngx_stream_lua-0.0.5/src/ngx_stream_lua_semaphore.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 1245
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/ngx_stream_lua-0.0.5/src/ngx_stream_lua_semaphore.h b/ngx_stream_lua-0.0.5/src/ngx_stream_lua_semaphore.h
|index 6841950..a4a2e54 100644
|--- a/ngx_stream_lua-0.0.5/src/ngx_stream_lua_semaphore.h
|+++ b/ngx_stream_lua-0.0.5/src/ngx_stream_lua_semaphore.h
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_shdict.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_sleep.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_sleep.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_socket_tcp.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_socket_tcp.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_socket_udp.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_socket_udp.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_ssl.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_ssl.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_ssl_certby.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_ssl_certby.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_string.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_string.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_time.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_time.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_timer.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_timer.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_uthread.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_uthread.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_util.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_util.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_variable.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_variable.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_worker.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_worker.h
patching file ngx_stream_lua-0.0.5/t/139-ssl-cert-by.t
patching file ngx_stream_lua-0.0.5/t/140-ssl-c-api.t
patching file ngx_stream_lua-0.0.5/t/cert/test2.crt
patching file ngx_stream_lua-0.0.5/t/cert/test2.key
patching file ngx_stream_lua-0.0.5/t/cert/test_ecdsa.crt
patching file ngx_stream_lua-0.0.5/t/cert/test_ecdsa.key

==> Formula
Tap: kong/kong
Path: /usr/local/Homebrew/Library/Taps/kong/homebrew-kong/Formula/openresty.rb
==> Configuration
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9ebbc474d816c5d0dda77117e74679e0cccb40aa
Core tap last commit: 15 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2, 1.8.0_181
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/pcre/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: kong/kong/openresty 1.13.6.2 did not build
Logs:
     /Users/apple/Library/Logs/Homebrew/openresty/01.nginx-1.13.6_03-log-tls.patch
     /Users/apple/Library/Logs/Homebrew/openresty/00.options.out
     /Users/apple/Library/Logs/Homebrew/openresty/02.ngx_stream_lua-0.0.5_06-ssl-cert.patch
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/kong/homebrew-kong/issues
"""

**Comment by JohnB520** [comment]
Same issue...

**Comment by ganeshs** [comment]
+1 I'm facing the same issue

**Comment by MichelinMan** [comment]
+1

**Comment by bungle** [comment]
It could be that patches are applied in wrong order.

**Comment by ganeshs** [comment]
@bungle is there a workaround for this?

**Comment by bungle** [comment]
@kartikey91 / @ganeshs,

We just release `1.0.1` which we tested with `Mojave` and it seemed to work. Can you try it now (with `brew up` first)?

**Comment by MichelinMan** [comment]
It works!
I did brew upgrade; brew install kong; and all the dependencies and patching went through with no errors. On Mojave 10.14.2.

Thank you!
Ioannis

**Comment by ganeshs** [comment]
It works. Thanks for the quick fix @bungle
