### ISSUE TITLE
macOS Mojave 10.14.2 brew install kong fail

### ISSUE THREAD

**Issue by tzssangglass** [Kong/homebrew-kong#87]
I have try mang ways to install kong by brew ,but fail ,and everytime reporting this issue:
Last 15 lines from /Users/xxxxxxx/Library/Logs/Homebrew/openresty/02.ngx_stream_lua-0.0.5_06-ssl-cert.patch:
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_timer.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_uthread.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_uthread.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_util.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_util.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_variable.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_variable.h
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_worker.c
patching file ngx_stream_lua-0.0.5/src/ngx_stream_lua_worker.h
patching file ngx_stream_lua-0.0.5/t/139-ssl-cert-by.t
patching file ngx_stream_lua-0.0.5/t/140-ssl-c-api.t
patching file ngx_stream_lua-0.0.5/t/cert/test2.crt
patching file ngx_stream_lua-0.0.5/t/cert/test2.key
patching file ngx_stream_lua-0.0.5/t/cert/test_ecdsa.crt
patching file ngx_stream_lua-0.0.5/t/cert/test_ecdsa.key
……

**Comment by nshntarora** [comment]
@thibaultcha Facing the exact same issue. Can you please help debug?

**Comment by bungle** [comment]
@tzssangglass / @nshntarora 

We just release `1.0.1` which we tested with `Mojave` and it seemed to work. Can you try it now (with `brew up` first)?

**Comment by tzssangglass** [comment]
> @tzssangglass / @nshntarora
> 
> We just release `1.0.1` which we tested with `Mojave` and it seemed to work. Can you try it now (with `brew up` first)?

it works , build kong success , thx
