### ISSUE TITLE
Install via brew fail 

### ISSUE THREAD

**Issue by sajov** [Kong/homebrew-kong#96]
Hi, no idea whats going on.
CONSOLE
mimetypes 1.0.0-2 is now installed in /usr/local/Cellar/kong/1.0.3 (license: MIT/X11)

kong-lapis 1.6.0.1-1 depends on pgmoon (not installed)
Installing https://luarocks.org/pgmoon-1.9.0-1.src.rock

pgmoon 1.9.0-1 is now installed in /usr/local/Cellar/kong/1.0.3 (license: MIT)

Cloning into 'lapis'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Operation timed out
github.com[1: 192.30.253.113]: errno=Operation timed out

Error: Failed installing dependency: https://luarocks.org/kong-lapis-1.6.0.1-1.rockspec - Failed cloning git repository.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/kong/homebrew-kong/issues

These open issues may also help:
brew install kong  failed https://github.com/Kong/homebrew-kong/issues/88
I can no longer install Kong 0.14 https://github.com/Kong/homebrew-kong/issues/94
 brew install --devel kong https://github.com/Kong/homebrew-kong/issues/79
0.14 no kong.conf https://github.com/Kong/homebrew-kong/issues/78
brew install kong fails (0.14.1) https://github.com/Kong/homebrew-kong/issues/83
kong 0.13.1-0 depends on luasec  0.6 not installed https://github.com/Kong/homebrew-kong/issues/73
error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com/kong/homebrew-kong/info/refs?service=git-upload-pack https://github.com/Kong/homebrew-kong/issues/68
Cannot install Kong via homebrew. [Failed installing dependency: https://luarocks.org/luasec-0.6-1.rockspec - Failed cloning git repository.] https://github.com/Kong/homebrew-kong/issues/50

**Comment by tholu** [comment]
Also looks like a network issue, or is this error persistent?

**Comment by josephbruni** [comment]
Are you working behind a corporate firewall that blocks port 9418?

**Comment by sajov** [comment]
problem is gone for no reason
thx
