### ISSUE TITLE
Error: Failed installing dependency: https://luarocks.org/lyaml-6.2.3-1.src.rock

### ISSUE THREAD

**Issue by imysm** [Kong/homebrew-kong#98]
==> /usr/local/opt/luarocks/bin/luarocks --tree=/usr/local/Cellar/kong/1.1.0 --lua-dir=/usr/local/opt/openresty/luaj
Last 15 lines from /Users/samyang/Library/Logs/Homebrew/kong/01.luarocks:
lua_system_constants.c:13:10: warning: 'luaL_newlib' macro redefined [-Wmacro-redefined]
# define luaL_newlib(L,l) (lua_newtable(L), luaL_register(L,NULL,l))
         ^
/usr/local/opt/openresty/luajit/include/luajit-2.1/lauxlib.h:125:9: note: previous definition is here
#define luaL_newlib(L, l)       (luaL_newlibtable(L, l), luaL_setfuncs(L, l, 0))
        ^
1 warning generated.
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -c lua_system_constants.c -o lua_system_constants.o
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -bundle -undefined dynamic_lookup -all_load -o lua_system_constants.so lua_system_constants.o
lua_system_constants 0.1.3-0 is now installed in /usr/local/Cellar/kong/1.1.0 (license: MIT)

kong 1.1.0-0 depends on lyaml 6.2.3 (not installed)
Installing https://luarocks.org/lyaml-6.2.3-1.src.rock

Error: Failed installing dependency: https://luarocks.org/lyaml-6.2.3-1.src.rock - Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/lyaml-6.2.3-1.src.rock - lyaml-6.2.3-1.src.rock

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/kong/homebrew-kong/issues

These open issues may also help:
brew install kong  failed https://github.com/Kong/homebrew-kong/issues/88
I can no longer install Kong 0.14 https://github.com/Kong/homebrew-kong/issues/94
 brew install --devel kong https://github.com/Kong/homebrew-kong/issues/79
0.14 no kong.conf https://github.com/Kong/homebrew-kong/issues/78
brew install kong fails (0.14.1) https://github.com/Kong/homebrew-kong/issues/83
kong 0.13.1-0 depends on luasec  0.6 not installed https://github.com/Kong/homebrew-kong/issues/73
error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com/kong/homebrew-kong/info/refs?service=git-upload-pack https://github.com/Kong/homebrew-kong/issues/68
Cannot install Kong via homebrew. [Failed installing dependency: https://luarocks.org/luasec-0.6-1.rockspec - Failed cloning git repository.] https://github.com/Kong/homebrew-kong/issues/50

**Comment by inarli** [comment]
please try this;
`brew install libyaml`

then 

`luarocks install lyaml YAML_DIR=/usr/local/Cellar/libyaml/0.2.2`
hint : YAML_DIR is libyaml package installed path.

may you need re-run the command. `brew install kong`

**Comment by imysm** [comment]
> please try this;
> `brew install libyaml`
> 
> then
> 
> `luarocks install lyaml YAML_DIR=/usr/local/Cellar/libyaml/0.2.2`
> hint : YAML_DIR is libyaml package installed path.
> 
> may you need re-run the command. `brew install kong`

thank you inarli
I do it by your way ，`brew install libyaml` and `luarocks install lyaml YAML_DIR=/usr/local/Cellar/libyaml/0.2.2`  are success。but re-run `brew install kong ` is failed.

`SamYangdeMacBook-Pro:~ samyang$ brew install libyaml
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
wget ✔              confluent-oss       hadolint            sdl
apache-arrow        dhall               jenkins             ssllabs-scan
apache-arrow-glib   dhall-json          juju                taskell
asdf                embulk              logtalk             vert.x
atomist-cli         get_iplayer         mps-youtube         xmake
cake                glib-networking     rakudo-star
cgal                gocr                ruby-build

==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles/li
######################################################################## 100.0%
==> Pouring libyaml-0.2.2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/libyaml/0.2.2: 9 files, 291.6KB
SamYangdeMacBook-Pro:~ samyang$ luarocks install lyaml YAML_DIR=/usr/local/Cellar/libyaml/0.2.2
Installing https://luarocks.org/lyaml-6.2.3-1.src.rock

/usr/local/opt/openresty/luajit/bin/luajit build-aux/luke package="lyaml" version="6.2.3" PREFIX="/usr/local/opt/kong/lib/luarocks/rocks-5.1/lyaml/6.2.3-1" CFLAGS="-O2 -fPIC" LIBFLAG="-bundle -undefined dynamic_lookup -all_load" LIB_EXTENSION="so" OBJ_EXTENSION="o" LUA="/usr/local/opt/openresty/luajit/bin/luajit" LUA_DIR="/usr/local/opt/kong/lib/luarocks/rocks-5.1/lyaml/6.2.3-1/lua" LUA_INCDIR="/usr/local/opt/openresty/luajit/include/luajit-2.1" YAML_DIR="/usr/local/Cellar/libyaml/0.2.2" YAML_INCDIR="/usr/local/Cellar/libyaml/0.2.2/include" YAML_LIBDIR="/usr/local/Cellar/libyaml/0.2.2/lib"
creating build-aux/config.ld
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -bundle -undefined dynamic_lookup -all_load  -I/usr/local/opt/icu4c/include -DNDEBUG -DPACKAGE='"lyaml"' -D_BSD_SOURCE -D_FORTIFY_SOURCE=2 -D_DARWIN_C_SOURCE -DVERSION='"6.2.3"' -Iext/include -I/usr/local/opt/openresty/luajit/include/luajit-2.1 -I/usr/local/Cellar/libyaml/0.2.2/include ext/yaml/yaml.c ext/yaml/emitter.c ext/yaml/parser.c ext/yaml/scanner.c -o macosx/yaml.so -L/usr/local/Cellar/libyaml/0.2.2/lib  -lyaml
true -c build-aux/config.ld .
/usr/local/opt/openresty/luajit/bin/luajit build-aux/luke install --quiet INST_LIBDIR="/usr/local/opt/kong/lib/luarocks/rocks-5.1/lyaml/6.2.3-1/lib" INST_LUADIR="/usr/local/opt/kong/lib/luarocks/rocks-5.1/lyaml/6.2.3-1/lua"
No existing manifest. Attempting to rebuild...
lyaml 6.2.3-1 is now installed in /usr/local/opt/kong (license: MIT/X11)`

-------
SamYangdeMacBook-Pro:~ samyang$ brew install kong
Error: /usr/local/opt/kong is not a valid keg
SamYangdeMacBook-Pro:~ samyang$ brew tap kong/kong
Updating Homebrew...
SamYangdeMacBook-Pro:~ samyang$ brew install kong
Updating Homebrew...
Error: /usr/local/opt/kong is not a valid keg
SamYangdeMacBook-Pro:~ samyang$ brew uninstall kong
Error: No such keg: /usr/local/Cellar/kong
SamYangdeMacBook-Pro:~ samyang$ which kong
SamYangdeMacBook-Pro:~ samyang$ kong
-bash: kong: command not found
SamYangdeMacBook-Pro:~ samyang$ /usr/local/opt/kong
-bash: /usr/local/opt/kong: is a directory
SamYangdeMacBook-Pro:~ samyang$ cd /usr/local/opt/kong
SamYangdeMacBook-Pro:kong samyang$ ll
total 0
drwxr-xr-x  3 samyang  admin    96B  4  2 21:30 share
drwxr-xr-x  4 samyang  admin   128B  4  2 21:30 lib
SamYangdeMacBook-Pro:kong samyang$

**Comment by inarli** [comment]
@imysm what is your brew version?
my brew info:
brew -v
```
Homebrew 2.0.6
Homebrew/homebrew-core (git revision f3521; last commit 2019-04-02)
Homebrew/homebrew-cask (git revision 37deeb; last commit 2019-04-02)
```
I just installed.
